services:
  db:
    container_name: SQL2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Wingplus*123"
    ports:
      - "1433:1433"
    hostname: SQL2022
    volumes:
      - sql_volume:/var/opt/mssql

volumes:
  sql_volume:
    name: sql_volume
